
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WPF_SQL
{

using System;
    using System.Collections.Generic;
    
public partial class Photo
{

    public int user_id { get; set; }

    public string Path { get; set; }

    public byte[] Binary { get; set; }



    public virtual Users Users { get; set; }

}

}
